org: freelandr
app: aws-kibworth
service: aws-kibworth
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  iam:
    role:
      statements:
        # Allow functions to interact with RDS
        - Effect: Allow
          Action: 
            - 'rds:Describe*'
            - 'rds:RestoreDBInstanceFromDBSnapshot'
            - 'rds:CreateDBSnapshot'
            - 'rds:DeleteDBSnapshot'
            - 'rds:DeleteDBInstance'
            - 'secretsmanager:GetSecretValue'
            - 'ec2:DescribeSecurityGroups'
            - 'ec2:DescribeSecurityGroupRules'
            - 'ec2:ModifySecurityGroupRules'
            - 'ec2:AuthorizeSecurityGroupIngress'
            - 'ec2:RevokeSecurityGroupIngress'
          Resource: '*'
functions:
  stop_rds:
    handler: src/stop_rds.lambda_handler
    timeout: 60
    events:
      - httpApi:
          path: /stop_rds
          method: post
  restore_rds:
    handler: src/restore_rds.lambda_handler
    timeout: 60
    events:
      - httpApi:
          path: /restore_rds
          method: post
